<h1><a href="https://www.youtube.com/watch?v=QUT1VHiLmmI">NumPy Tutorial</a></h1>

<h3>Import NumPy</h3>

In [1]:
import numpy as np

<h3>Basics</h3>

In [2]:
# 1D Array
a = np.array([1, 2, 3], dtype=np.int16)  # Specify Data Type
print(a)

[1 2 3]


In [3]:
# 2D Array
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Array Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get Array Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get Data Type
print(a.dtype)
print(b.dtype)

int16
float64


In [7]:
# Get Memory Size of an Element
print(a.itemsize)
print(b.itemsize)

2
8


In [8]:
# Get Size of Array
print(a.size)
print(b.size)

3
6


In [9]:
# Get Size of Array (Number of Bytes)
print(a.nbytes)  # Same as (a.size * a.itemsize)
print(b.nbytes)

6
48


<h3>Accessing / Updating Specific Elements</h3>

In [10]:
# Create and Fill the Array
a = np.array([np.arange(1, 7 + 1), np.arange(8, 14 + 1)])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get Specific Element [r, c]
print(a[1, 5])

13


In [12]:
# Get Specific Row
print(a[0, :])

[1 2 3 4 5 6 7]


In [13]:
# Get Specific Column
print(a[:, 0])

[1 8]


In [14]:
# Grab Specific Elements
# [start_index:end_index:step_size]
print(a[0, 1:6:2])

[2 4 6]


In [15]:
# Update Element(s)
a[1, 5] = 20
print(a)
print()

a[:, 2] = 25
print(a)
print()

a[:, 2] = [69, 420]
print(a)
print()

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

[[ 1  2 25  4  5  6  7]
 [ 8  9 25 11 12 20 14]]

[[  1   2  69   4   5   6   7]
 [  8   9 420  11  12  20  14]]



<h3>Initialise Different Types of Arrays</h3>

In [16]:
# All 0s Matrix
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [17]:
# All 1s Matrix
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Fill Matrix with Other Number
print(np.full((4, 2), 23))

[[23 23]
 [23 23]
 [23 23]
 [23 23]]


In [19]:
# Fill Pre Existing Matrix with Other Number
a = np.array([69, 420, 123])
print(np.full_like(a, 23))

[23 23 23]


In [20]:
# Generate Random Decimals
print(np.random.rand(4, 2))
print()

a = np.array([69, 420, 123])
print(np.random.random_sample(a.shape))

[[0.81128729 0.77609161]
 [0.27491283 0.84046372]
 [0.08712372 0.48941418]
 [0.73295967 0.00093195]]

[0.6016451  0.2431224  0.72788621]


In [21]:
# Generate Random Integers
print(np.random.randint(4, 7 + 1, size=(3, 4, 2)))

[[[6 5]
  [4 7]
  [5 6]
  [5 5]]

 [[7 7]
  [5 5]
  [4 6]
  [6 7]]

 [[6 6]
  [7 6]
  [6 6]
  [5 6]]]


In [22]:
# Identity Matrix
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# Repeat Array
a = np.array([1, 2, 3])
print(np.repeat(a, 3))  # Default Axis is 1

a = np.array([[1, 2, 3]])
print(np.repeat(a, 3, axis=0))

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


<h3><a href="https://youtu.be/QUT1VHiLmmI?t=1915">Exercise at 31:55</a></h3>

In [24]:
arr_1 = np.ones((5, 5))
arr_2 = np.zeros((3, 3))
arr_2[1, 1] = 9
arr_1[1:4, 1:4] = arr_2
arr_1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

<h3>Array Copying</h3>

In [25]:
# 'Copying' an Array
a = np.array([1, 2, 3])
b = a  # Both 'a' and 'b' are pointing to the same memory address
print(a)
print(b)
print()

b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]

[100   2   3]
[100   2   3]


In [26]:
# Making a Shallow Copy of the Array
# NOTE : Makes Shallow Copies of Python Objects in Array
# NOTE : Will Result in same issues as above cells for these Objects

# Part 1
print("Part 1")
a = np.array([1, 2, 3])
b = a  # Both 'a' and 'b' are pointing to the same memory address
print(a)
print(b)
print()

b[0] = 100
print(a)
print(b)
print()

# Part 2
print("Part 2")
a = np.array([1, 2, 3, [4, 5, 6]], dtype=object)
b = a.copy()
print(a)
print(b)
print()

b[0] = 100  # Update 1st Element of array 'b'
b[-1][0] = 10  # Update Last Element of array 'b'
print(a)
print(b)

Part 1
[1 2 3]
[1 2 3]

[100   2   3]
[100   2   3]

Part 2
[1 2 3 list([4, 5, 6])]
[1 2 3 list([4, 5, 6])]

[1 2 3 list([10, 5, 6])]
[100 2 3 list([10, 5, 6])]


In [27]:
# Making a Deep Copy of the Array
# The issues in the previous two cells won't occur
import copy

a = np.array([1, 2, 3, [4, 5, 6]], dtype=object)
b = copy.deepcopy(a)
print(a)
print(b)
print()

b[0] = 100
b[-1][0] = 10
print(a)
print(b)

[1 2 3 list([4, 5, 6])]
[1 2 3 list([4, 5, 6])]

[1 2 3 list([4, 5, 6])]
[100 2 3 list([10, 5, 6])]


<h3>Mathematics</h3>

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
print(a)

[1 2 3 4]


In [29]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)
print()

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print()

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]

[2 2 4 4]
[0 2 2 4]
[1 0 3 0]
[ 1. inf  3. inf]

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


/Users/keshav/Downloads/LearnNumPy/venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


In [30]:
# Matrix Multiplication
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print(b)
print()

print(np.matmul(a, b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]

[[6. 6.]
 [6. 6.]]


In [31]:
# Determinant of Matrix
c = np.identity(3)
print(np.linalg.det(c))

1.0


<h3>Statistics</h3>

In [32]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [33]:
# Smallest Value
print(np.min(stats))
print(np.min(stats, axis=1))

1
[1 4]


In [34]:
# Biggest Value
print(np.max(stats))

6


In [35]:
# Sum of All Elements
print(np.sum(stats))

21


<h3>Reorganising Arrays</h3>

In [36]:
# Change Array Shape
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.shape)
print()

after = before.reshape((2, 2, 2))
print(after)
print(after.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [37]:
# Vertically Stacking Vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(v1)
print(v2)
print(np.vstack([v1, v2]))

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [38]:
# Horizontally Stacking Vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)
print(np.hstack([h1, h2]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


<h3>Miscellaneous</h3>

In [39]:
# Load Data From Files (w/o Pandas)
file_data = np.genfromtxt("data.txt", delimiter=",")
print(file_data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [40]:
# Boolean Masking
print((file_data > 50) & (file_data < 100))

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]


In [41]:
# Advanced Indexing
print(file_data[file_data > 50])

[196.  75. 766.  75.  55. 999.  78.  76.  88.]


<h3><a href="https://youtu.be/QUT1VHiLmmI?t=3360">Exercise at 56:00</a></h3>

In [42]:
# Generate Matrix
matrix = np.arange(1, 30 + 1)
matrix = matrix.reshape((6, 5))
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [43]:
# Question 1
print(matrix[2:3 + 1, 0:1 + 1])
print()

[[11 12]
 [16 17]]



In [44]:
# Question 2
a = matrix[0:3 + 1, 1:4 + 1]
print(np.diagonal(a))

# OR
a = matrix[[0, 1, 2, 3], [1, 2, 3, 4]]
print(a)

[ 2  8 14 20]
[ 2  8 14 20]


In [45]:
# Question 3
b = matrix[:, 3:]
print(b[[0, -2, -1]])

# OR
b = matrix[[0, 4, 5], 3:]
print(b)

[[ 4  5]
 [24 25]
 [29 30]]
[[ 4  5]
 [24 25]
 [29 30]]
